# Cloudflare Pages configuration for Chiso's Cookbook
name = "portfolio"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[build]
command = "npm run build"
output_directory = "dist"

[site]
bucket = "./dist"

[env.production]
name = "portfolio"

[env.preview]
name = "portfolio-preview"
