# Cloudflare Pages configuration for Chiso's Cookbook
name = "portfolio"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

# Pages-specific configuration
[pages]
build_output_directory = "dist"
compatibility_date = "2023-12-01"

# KV Namespace for blog comments
kv_namespaces = [
  { binding = "KV_COMMENTS", id = "b45ba16ccf9c4fb7b8439f6ca4976b02" },
  { binding = "KV_RECIPE_NOTES", preview_id = "recipe_notes_preview", id = "recipe_notes_production" }
]

# Environment-specific configurations
[env.production]
name = "portfolio" 

[env.preview]
name = "portfolio-preview"
